apiVersion: v1
kind: ConfigMap
metadata:
  name: kelp-config
  labels:
    app: kelp-dev
data:
  custom_config.cfg: |
    # Sample custom config file for the kelp bot
    #auth0
    AUTH0_ENABLED=false

    #auth0 domain
    DOMAIN="dev-orunpay.eu.auth0.com"  #"domain_goes_here" #example "dev-*******.eu.auth0.com"

    #auth0 clientID
    CLIENT_ID="4wsfguulhcHdXSAN3NmvUDSljAag59WR"    #"Client_id_goes_here" #examples "7I47ob2************XKF29hY5"

    #auth0 audience
    AUDIENCE="https://qa.api.orunpay.com/v1"   #"AUdience_goes_here"



    #[DELEGATED]

    #delegated things here
    DELEGATED_ENABLED=true

    #delegated signing url here
    DELEGATED_SIGNING_URL="https://orunpay-api.herokuapp.com/v1/transactions/sep0007"

    #delegated callback url here
    CALLBACK_URL="callback_url_goes_here"
